### PR TITLE
Shows more info and list multiple linux distros

### PR DESCRIPTION
**Pull request by marcosdiez**
Hi,

I decided to play with p9 as well and your project seemed an interesting way to start with.

Marcos

### CODE REVIEW

**Comment by Biswa96** [comment]
Thank you for this contribution. May you edit two things? 1. It's `NETRESOURCEW` not `NETRESOURCEA`. I know its not so important, just to make all type same. 2. Also use switch/case with `dwUsage`.

**Comment by marcosdiez** [comment]
Hi,

sorry for using `NETRESOURCEA` instead of `NETRESOURCEW`.

I got the reference from the results from https://docs.microsoft.com/en-us/windows/desktop/api/npapi/nf-npapi-npenumresource which pointed me to the former.

That being said, https://docs.microsoft.com/en-us/windows/desktop/api/winnetwk/ns-winnetwk-_netresourcew and https://docs.microsoft.com/en-us/windows/desktop/api/winnetwk/ns-winnetwk-_netresourcea shows they are the same so I guess it does not matter. I replaced anyway.

About not using a switch statement for  `dwUsage`, this is actually by design. The documentation ( https://docs.microsoft.com/en-us/windows/desktop/api/winnetwk/ns-winnetwk-_netresourcew ) says that field is a bitmask hence it can actually contain both values. I did add an `if` to show the results only if `dwScope == RESOURCE_GLOBALNET`, as the documentation suggested.

One further question: were you able to mount arbitrary p9 servers on the latest windows 10 ?

**Comment by Biswa96** [comment]
What do you mean by "arbitrary p9 servers"? Really I am not investigating this section because the upcoming WSL2 may add many things. So, I'm waiting for that release.

**Comment by marcosdiez** [comment]
I mean, can I mount my phone, my non WSL virtual machine, my other computer, etc ?

**Comment by Biswa96** [comment]
Ooo... I do not know that. But I will definitely look into it. Thank you! Merging...

**Comment by Biswa96** [comment]
The while loop may not necessary here.

**Comment by marcosdiez** [comment]
I believe it is. According to 
https://docs.microsoft.com/en-us/windows/desktop/api/npapi/nf-npapi-npenumresource


    Return Value

If the function succeeds, it should return WN_SUCCESS. The caller may 
continue to call *NPEnumResource* to continue the enumeration. 
Otherwise, it should return one of the following error codes.

What I can see, though, is that it may return *WN_MORE_DATA *and we are 
not properly dealing with it.

So we actually need a switch statement to handle all that.

I might do at night.
**

**Comment by Biswa96** [comment]
I was wrong. Apology to interrupt. The code is OK.

**Comment by Biswa96** [comment]
Before doing any change, It will be better if you contact me with my email. It's in my profile page. I found something cool...

**Pull request merged**
